### PR TITLE
Add configuration for Symfony 4.3 (and 5.0) compatibility.

### PR DESCRIPTION
**Pull request by mumia**

### CODE REVIEW

**Comment by lunetics** [comment]
We need either to raise the minimum symfony requirement to 4.3 or use a BC layer e.g.
```php
        if (method_exists($treeBuilder, 'getRootNode')) {
            $rootNode = $treeBuilder->getRootNode();
        } else {
            // BC layer for symfony/config 4.1 and older
            $rootNode = $treeBuilder->root('doctrine');
        }
        $rootNode    = $treeBuilder->getRootNode();
```

**Comment by codeliner** [comment]
@lunetics such a check is included in the PR. phpstan has a problem with the non existing 'getRootNode' method. A phpstan exclude rule would be good: https://github.com/phpstan/phpstan#ignore-error-messages-with-regular-expressions

Anyway, prooph/service-bus is deprecated and will soon be archived. Projects should migrate to symfony/messenger instead.

**Comment by enumag** [comment]
@codeliner 

> Anyway, prooph/service-bus is deprecated and will soon be archived.

It would still be helpful to have SF 5 support here. I'm working hard on moving away from `prooph/service-bus` but it is a part of much larger refactoring which will take a few more months. I'd like to upgrade to SF 5 anyway.

> Projects should migrate to symfony/messenger instead.

As far as I can tell Messenger can't work in async environment, making it incompatible with `prooph/event-store-client` and therefore useless.

**Comment by enumag** [comment]
ping @codeliner

**Comment by szepczynski** [comment]
ping

**Comment by codeliner** [comment]
Ok, I've merged the PR, but again prooph/service-bus reached end of live. I do a final release for the bundle.

**Comment by webdevilopers** [comment]
Thank you @codeliner . When I understand this correctly this PR does add support for Symfony 4. But Symfony is still no supported yet as mentioned in:

* https://github.com/prooph/service-bus-symfony-bundle/issues/82

@enumag Have you managed to for instance migrate the event bus routes to symfony messenger?

Here is the solution that seems to work for us in order to use the symfony messenger event bus inside the event publisher:

* https://gist.github.com/webdevilopers/5903d2c217aea5fbe31a3b86e13ee9da

**Pull request merged**
