### PR TITLE
PSR Logger plugin messages accuracy improvements

### PR DESCRIPTION
**Pull request by gquemener**
Several messages were in the present tense whereas they should be in the past tense.

The logged message was inaccurate in case of an event dispatching:
```
before
> Dispatching event "App\Acme\Domain\MyEvent" to handler

after
> Dispatching event "App\Acme\Domain\MyEvent" to listeners "foo, bar, baz"
```

I've also wrapped all message names with double quotes.

### CODE REVIEW

**Comment by gquemener** [comment]
Hello,

I've just rebased this branch to include earliest `master` commits.

Have you had the chance to give some thoughts about it @UFOMelkor ?
Please let me know if anything disturbs you, so that I can work on it.

Thanks!

**Comment by codeliner** [comment]
@gquemener Do you know how to fix the failing tests? Can be done in a separate PR, if you think that's better

**Edit:** Ok, did not see your issue: https://github.com/prooph/service-bus-symfony-bundle/issues/79
I'm also out of ideas how to solve that :(

**Comment by gquemener** [comment]
@codeliner I think it's worth it to deal with the issue #79 in another PR. My guess is that it's a mix of Symfony / Prooph bundle bugs.

Furthermore, the testsuite is already broken on master, so merging this PR will not hurt.

I keep investigating.

**Comment by codeliner** [comment]
:thinking: @gquemener I've merged the open PRs and fixed a conflict in this PR. My hope was that pipeline is green now but master is broken as well as your PR. Any ideas?

Would like to do one last release for this package, before we stop supporting it.

**Comment by gquemener** [comment]
Hello @codeliner,

The whole testsuite is broken due to some changes within Symfony DI. It looks like these changes were not BC, and I am not sure if this is a problem in the version constraints that are set in the `composer.json` or problems within this bundle.

However, I've started to fill holes on a branch. I guess I need a few weeks to fix all this mess on my spare time. How long d'you give me? ^^

**Comment by gquemener** [comment]
https://github.com/prooph/service-bus-symfony-bundle/pull/83

**Comment by gquemener** [comment]
Closing due to inactivity

**Pull request closed without merging**
