### PR TITLE
Initial documentation

### PR DESCRIPTION
**Pull request by UFOMelkor**
Please review and give feedback – and correct my bad english ;-)

### CODE REVIEW

**Comment by sandrokeil** [comment]
Awesome work. :+1: For me it's great. If you have finished, I will merge it. Thank you very much.

**Comment by mablae** [comment]
@sandrokeil Could you please merge this as I want to work on adding more documentation? Thanks.

**Comment by codeliner** [comment]
you're welcome @mablae ;)

**Comment by codeliner** [comment]
@mablae @UFOMelkor [this one](https://github.com/prooph/event-store-symfony-bundle) could need some of this great work here, too ;)

**Pull request merged**
