### PR TITLE
More symfony friendly configuration

### PR DESCRIPTION
**Pull request by UFOMelkor**
Hey guys,

thank you for the great work you are doing on prooph.
I really enjoy using it and the documentation and the do-applications help a lot to learn it.
But configuring prooph in symfony does not really make fun. It feels more like a ZF2 configuration than a symfony one. I'll try to fix this with two things:
1. Enable autocompletion
   For PhpStorm there is a great Symfony2 plugin which offers autocompletion for configuration files.
   Autocompletion for services in YAML is triggered by an `@`. Allowing an `@` before service ids helps a lot.
2. Route with tagging
   The Routing is difficult in two ways. First it references the handler which means I have to know how the handler is named or copy and paste its name (may be solved by autocompletion).
   Second as the message names of the routes are often class names, they must be adjusted if the class is refactored. This is annoying because we could not simply use the `::class` constant as we are not in PHP but in YAML/XML.
   Therefore I added a compiler pass that looks for tagged services and
   - collects all methods with a single parameter of type `Prooph\Common\Messaging\Message`
   - and adds the service to the message names of all found messages.

Perhaps this is a little bit to much magic (or should be separated in another bundle), but before doing further work I would like to hear your feedback :-)

### CODE REVIEW

**Comment by prolic** [comment]
there are php-cs issues

**Comment by UFOMelkor** [comment]
Fixed

**Comment by sandrokeil** [comment]
@UFOMelkor Thank you very much. Hope I can take a deep look next week and can give you some feedback.

**Comment by UFOMelkor** [comment]
Thank you :-)

**Comment by codeliner** [comment]
@UFOMelkor awesome. exactly the feedback we need :+1: 
If @sandrokeil is not faster I try to look at your PR next week. atm I'm under load :)
Would also be nice if @rommsen can take a short look?

**Comment by rommsen** [comment]
Yeah looks really cool. Will have at least a short look over it next week

**Comment by codeliner** [comment]
@UFOMelkor Sorry for not getting back to you earlier but last week was a bit heavy :D

I'm totally fine with the first change.
The second one is really black magic and I'm not sure about it. I see the benefits and I like them but what happens if message name is generated at runtime depending on constructor parameters?
Can we have a "black magic enabled" config option or something which is off by default?
I know that configuration can be pain (especially when you don't have php language constructs available)
but it is also the safest way to control complex things like messaging. It is a good thing when you can look at a config file and see the message routing in one place.
With a config option and a short explanation in the docs I'd be glad to merge the second option, too ;)
Thx for your great work. Do you have ideas for the event-store-symfony-bundle, too?

**Comment by UFOMelkor** [comment]
How about this:

``` yml
    my_handler:
        class: Acme\MyHandler
        tags:
            - { name: 'prooph_service_bus.my_command_bus.route_target', message: 'my' }
```

If the message parameter is omitted, it will try to automatically detect the message. So both will be possible, automatic and manual configuration without a global config option.

**Comment by codeliner** [comment]
@UFOMelkor sounds good

**Comment by UFOMelkor** [comment]
I've added the possibility to configure the message explicitly.
Next step would be documentation. Because currently there is no documentation I would prefer to open a new PR for the initial documentation.

**Comment by codeliner** [comment]
@UFOMelkor merged! Thank you again for your great work. Documentation would be awesome :+1: 
I've blocked more time this month for OSS so next PR will be merged more quickly. Promised ;)

**Pull request merged**
