### PR TITLE
Start using the class name for handler services (in the documentation)

### PR DESCRIPTION
**Pull request by coudenysj**
As introduced in https://symfony.com/blog/new-in-symfony-3-3-optional-class-for-named-services
See https://symfony.com/doc/current/best_practices/business-logic.html#services-naming-and-configuration

### CODE REVIEW

**Comment by sstok** [comment]
Looks good to me 👍

**Comment by UFOMelkor** [comment]
Thanks @coudenysj for your contribution 👍 
Please remove the `public` attributes. While it's correct that they are currently necessary, the next release will not require them anymore. See #56 for more information.

**Comment by coudenysj** [comment]
@UFOMelkor Done

**Comment by UFOMelkor** [comment]
Thank you!

**Pull request merged**
